spring.application.name=radarinvest-api
info.app.version=@project.version@

# Database Configuration (File based to persist data)
# em memoria spring.datasource.url=jdbc:h2:mem:radarinvest;DB_CLOSE_DELAY=-1
spring.datasource.url=jdbc:h2:file:./data/radarinvestdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Postgres Configuration (Matches docker-compose)
# spring.datasource.url=jdbc:postgresql://localhost:5432/radarinvest
# spring.datasource.username=radarinvest
# spring.datasource.password=secret
# spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.show-sql=true

# update - mantem os dados; create - apaga tudo e cria; drop - apaga tudo
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true

# Server
server.port=8080
server.servlet.context-path=/radarinvest

# Logging
logging.level.br.com.edneysiqueira.radarinvest=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Brapi.dev Provider
radar.provider.brapi.url=https://brapi.dev/api
radar.provider.brapi.token=4JtzzSosPSTSNv7Q6sKXpb

# Active Provider: crawler: Usa o Investidor10, brapi: Usa a API da Brapi, mock: Usa dados falsos
radar.provider.active=crawler

# Swagger / OpenAPI
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs
